knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            #page-size: A4
            #dpi: 300
            #image-quality: 80
            margin-left: 30mm
            #margin-right: 15mm
            #margin-top: 15mm
            #margin-bottom: 15mm
            #user-style-sheet: %kernel.root_dir%/../web/assets/css/pdf.css
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
