twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        public_path: '%kernel.project_dir%/public'
        tax_value: '%env(VALUE_IVA)%'
        oauthGoogleId: '%env(OAUTH_GOOGLE_ID)%'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
