twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        public_path: '%kernel.project_dir%/public'
        app_env: '%env(APP_ENV)%'
        tax_value: '%env(VALUE_IVA)%'

when@test:
    twig:
        strict_variables: true
