language: php
dist: bionic

matrix:
  fast_finish: true
  include:
    - php: 8.1.0
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - nvm install 12
  - yarn install
  - yarn dev
