language: php

matrix:
  fast_finish: true
  include:
    - php: 8.1.0
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - npm i
  - npm run build

script:
  - composer test
