language: php
dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 8.1.0
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - nvm install 12
  - yarn install
  - yarn dev
  - bin/console doctrine:database:create -n --env=test
  - bin/console doctrine:migrations:migrate -n --env=test
  - bin/console doctrine:fixtures:load -n --env=test

script:
  - SYMFONY_DEPRECATIONS_HELPER=disabled ./bin/phpunit $PHPUNIT_FLAGS
