<?php

namespace App\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    /**
     * @param int $storeId
     * @param int $year
     *
     * @return array
     */
    public function findContracts($storeId = 0, $year = 0)
    {
        $query = $this->createQueryBuilder('c');

        $query->where('c.id > 1');

        if ($storeId) {
            $query->andWhere('c.storeNumber = :storeId')
                ->setParameter('storeId', $storeId);
        }

        if ($year) {
            $query->andWhere('YEAR(c.date) = :year')
                ->setParameter('year', $year);
        }

        $query->addOrderBy('c.date', 'DESC');
        $query->addOrderBy('c.storeNumber', 'ASC');

        return $query
            ->getQuery()
            ->getResult();
    }

    /**
     * @return mixed
     */
    public function findPlantilla()
    {
        $data = $this->matching(
            Criteria::create()->where(
                Criteria::expr()->eq('id', 1)
            )
        );

        return $data[0];
    }
}
