# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $rootDir: '%kernel.project_dir%'
            $appEnv: '%env(APP_ENV)%'
            $defaultLocale: '%env(APP_LOCALE)%'
            $listLimit: '%env(LIST_LIMIT)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TaxService:
        $taxValue: '%env(VALUE_IVA)%'

    App\Service\EmailHelper:
        $emailFromAddress: '%env(EMAIL_FROM_ADDR)%'
        $emailFromName: '%env(EMAIL_FROM_NAME)%'

    App\DataCollector\GitDataCollector:
        tags:
            -   name: data_collector
                template: 'data_collector/git_data.html.twig'
                id: 'app.git_data_collector'
        public: false

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: [ 'doctrine.fixture.orm' ]
